services:
  app:
    build: 
      context: ..
      dockerfile: Dockerfile

    env_file:
      - ../.env
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - ../app/:/app/

    command: python main.py