version: "3.9"


services:
  app:
    build: 
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    volumes:
      - ../app/:/app/

    command: python web_app.py