version: '3.9'

services:

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME:?}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD:?}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DATABASE_USERNAME:?}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DATABASE_PASSWORD:?}
      ME_CONFIG_MONGODB_URL: mongodb://${DATABASE_USERNAME:?}:${DATABASE_PASSWORD:?}@mongo:27017/
      ME_CONFIG_BASICAUTH: false


volumes:
  dbdata6: