version: "3.9"


services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    depends_on:
      - certbot
    networks:
      - shared_network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx/ssl:/etc/letsencrypt
      - ../nginx/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ../nginx/ssl:/etc/letsencrypt
      - ../nginx/www:/var/www/certbot
    networks:
      - shared_network

networks:
  shared_network:
    external: true